# to avoid problem with black screen
# Edit appropriate file for your situation
/usr/share/applications/google-chrome.desktop
/usr/share/applications/chromium-browser.desktop
# ust append the flag (-disable-gpu) to the end of the three Exec= lines in your file.
...
Exec=/usr/bin/google-chrome-stable %U -disable-gpu
...
Exec=/usr/bin/google-chrome-stable -disable-gpu
...
Exec=/usr/bin/google-chrome-stable --incognito -disable-gpu
...
